### Sign up
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "email": "thanhnhanstudy@gmail.com",
    "name": "Thanh Nhan",
    "password": "12345678",
    "confirmPassword": "12345678"
}

### Verify sign up
POST http://localhost:3000/auth/verify-signup?code=205179&email=thanhnhanstudy@gmail.com


### Resend verify code
POST http://localhost:3000/auth/resend-verify-code?email=thanhnhanstudy@gmail.com&purpose=RESET_PASSWORD

### Reset password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
    "email": "thanhnhanstudy@gmail.com",
    "code": "235982",
    "password": "thanhnhan"
}

### Sign in
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
    "email": "thanhnhanstudy@gmail.com",
    "password": "0914220605"
}

### Refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTkzZTNlYjZmYTI3ZTQ1YWIwZjdjYjUiLCJyb2xlIjoidXNlciIsInN0YXR1cyI6ImFjdGl2ZSIsInZlcmlmaWVkIjpmYWxzZSwiZW1haWwiOiJ0aGFuaG5oYW5zdHVkeUBnbWFpbC5jb20iLCJpYXQiOjE3MDQyMTE5NDEsImV4cCI6MTcwNDgxNjc0MX0.s6lK5fc4U0QYR2TOuBuLU7K4H4-p2gserrnTWhgy0ks

### Get user info

### Test email
GET http://localhost:3000/auth/test
Content-Type: application/json

### Get pre-signed url for avatar
GET http://localhost:3000/auth/profile/avatar/presigned-url
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRiMDBkNWI4MWFjMDU5Nzc0Mjk2ZTciLCJyb2xlIjoidXNlciIsInN0YXR1cyI6ImFjdGl2ZSIsInZlcmlmaWVkIjp0cnVlLCJlbWFpbCI6InRoYW5obmhhbnN0dWR5QGdtYWlsLmNvbSIsImlhdCI6MTcxMDQwMTQzNywiZXhwIjoxNzEwNDg3ODM3fQ.ccb8TQULJesNYViga6LIw4kVjYPaS-Dd5Nk_9JMsr6k