### Add item to cart
POST http://localhost:3000/carts/
Content-Type: application/json
Authorization: {{token}}

{
  "productId": "6597754a7ecfb67259dd7cc8",
  "quantity": 2,
  "price": 1299.99,
  "productName": "Ultra HD Smart TV",
  "ownerId": "6593e3eb6fa27e45ab0f7cb5"
}

### Remove item out of cart
DELETE http://localhost:3000/carts/items/65968c30199a454054a0df89
Content-Type: application/json
Authorization: {{token}}

{
  "productId": "6596c29b8860b8a9e5d24697",
  "quantity": 1,
  "price": 19.99,
  "productName": "Nhan Hoang edited",
  "ownerId": "6593e3eb6fa27e45ab0f7cb5"
}

### Empty cart
PUT http://localhost:3000/carts/empty
Content-Type: application/json
Authorization: {{token}}

### Get cart
GET http://localhost:3000/carts/
Content-Type: application/json
Authorization: {{token}}

### Update item quantity in cart
PATCH http://localhost:3000/carts/items/6596c29b8860b8a9e5d24697
Content-Type: application/json
Authorization: {{token}}

{
  "quantity": 5
}