### Create comment 1
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: {{token}}

{
  "content": "This is a comment 1",
  "productId": "65968c30199a454054a0df89"
}

### Create comment 2
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: {{token}}

{
  "content": "This is a comment 2",
  "productId": "65968c30199a454054a0df89"
}

### Create comment 1.1
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: {{token}}

{
  "content": "This is a comment 1.1",
  "productId": "65968c30199a454054a0df89",
  "parentCommentId": "65a55704d7581f8313d71b31"
}

### Get Comments
GET http://localhost:3000/comments?page=1&limit=10&productId=65968c30199a454054a0df89&parentCommentId=65a548d3e00e4a61b459ffa8
Content-Type: application/json
Authorization: {{token}}

### Delete Comment
DELETE http://localhost:3000/comments/65a55704d7581f8313d71b31
Content-Type: application/json
Authorization: {{token}}