### Review checkout
POST http://localhost:3000/orders/review
Content-Type: application/json
Authorization: {{token}}

{
  "discountCodes": ["CLOTHES20"]
}


### Checkout
POST http://localhost:3000/orders/checkout
Content-Type: application/json
Authorization: {{token}}

{
  "discountCodes": ["CLOTHES20"],
  "deliveryAddress": {
    "address": "Linh Dog",
    "city": "Thu Duc",
    "name": "Nhan Thanh",
    "phone": "0984909703",
    "isPrimary": true
  }
}

### Get my orders
GET http://localhost:3000/orders/my-orders
Content-Type: application/json
Authorization: {{token}}

### Get order detail
GET http://localhost:3000/orders/6603b38e382ebd6cfe07c92b
Content-Type: application/json
Authorization: {{token}}

### Change order product status
POST http://localhost:3000/orders/6603b38e382ebd6cfe07c92b/6603b38e382ebd6cfe07c92b/shipping
Content-Type: application/json
Authorization: {{token}}